apiVersion: v1
kind: Pod
metadata:
    name: nginx-config-pod
spec:
    containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
      - name: test-vol
        mountPath: /etc/configmap
    volumes:
      - name: test-vol
        configMap:
           name: nginx-demo #name_of_configmap_created 
           items:
           - key: file_1.txt
             path: file_1.txt
