apiVersion: v1
kind: Pod
metadata:
    name: nginx-secret-pod
spec:
    containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
      - name: test-vol
        mountPath: /etc/secret
    volumes:
      - name: test-vol
        secret:
           secretName: demo-secret

